export const products = [
    {
      id: 1,
      name: "Kemeja Korduroi Untuk Pria Atasan Streetwear Antik Musim Gugur Musim Semi",
      category: "Baju",
      price: "13",
      image: "/images/products/baju-1.png",
      isCart: false,
      description: "This shirt features a vibrant and eye-catching color and a solid pattern that will give you a happy feeling. Its long sleeve design makes it an ideal choice for men. The turn-down collar adds to comfort and stylish look. Its versatile design and great fit make it an ideal choice for casual occasions. Specifications Style: Casual Sleeve Style: Regular Sleeve Length(cm): Full Shirts Type: Casual Shirts Pattern Type: Solid Origin: CN(Origin) Model Number: C6112 Material: Cotton Item T",
    },
    {
      id: 2,
      name: "Ventela Public Low Yellow Original",
      category: "Sepatu",
      price: "10",
      image: "/images/products/sepatu-2.png",
      isCart: false,
      description: "Regular fit Denim design Classic collar Long buttoned sleeve Patch pocket on the chest Button up The model is 187 cm tall and is wearing a size M",
    },
    {
      id: 3,
      name: "Ricardo RICARDO D'Britano Kemeja Polynosic Lengan Panjang Polos 22267",
      category: "Baju",
      price: "11",
      image: "/images/products/baju-3.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 4,
      name: "High Street Jeans Pria Mode Retro Biru Muda Robek Skinny Fit",
      category: "Celana",
      price: "17",
      image: "/images/products/celana-4.png",
      isCart: false,
      description: "Rugged, functional, and to the point. The Operator Utility Shirt has a military look with a metropolitan fit and finish. The durable stone gray cotton shirt weight canvas is sure to be a favorite back to well-worn denim.",
    },
    {
      id: 5,
      name: "Jaket Kasual Saku Ganda Cetak Lengan Huruf Patchwork Pria Modis dan Kasual",
      category: "Baju",
      price: "18",
      image: "/images/products/baju-5.png",
      isCart: false,
      description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
      id: 6,
      name: "Jaket Denim Kasual Bermotif Grafis - Jeans Biru",
      category: "Baju",
      price: "19",
      image: "/images/products/baju-6.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 7,
      name: "Kaninna Scarf SAKURA Premium Voal Scarf Hijab Lasercut",
      category: "Hijab",
      price: "5",
      image: "/images/products/hijab-1.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 8,
      name: "Jam Tangan Patek Philippe Steel Edisi Terbatas",
      category: "Jam",
      price: "21",
      image: "/images/products/jam-1.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 9,
      name: "Ventela Basic High Denim Black - 38",
      category: "Sepatu",
      price: "17",
      image: "/images/products/sepatu-1.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 10,
      name: "Kemeja Flanel Pria Kotak Terbaru Formal Casual",
      category: "Baju",
      price: "12",
      image: "/images/products/baju-2.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 11,
      name: "Ventela Basic Low All White Original",
      category: "Sepatu",
      price: "15",
      image: "/images/products/sepatu-3.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 12,
      name: "Balmain Paris Jeans Celana Motor Hitam",
      category: "Celana",
      price: "14",
      image: "/images/products/celana-2.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 13,
      name: "Chrono MOdern PVD Black Jam Tangan Pria",
      category: "Jam",
      price: "17",
      image: "/images/products/jam-2.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 14,
      name: "Jaket Jeans Oversize Robek Pria",
      category: "Baju",
      price: "14",
      image: "/images/products/baju-4.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 15,
      name: 'Original Celana Denim 5 Saku - "Classic Jusac" Fit',
      category: "Celana",
      price: "18",
      image: "/images/products/celana-3.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 16,
      name: "Balmain Blue Jeans - Biru Muda",
      category: "Celana",
      price: "21",
      image: "/images/products/celana-1.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 17,
      name: "Kaninna Scarf FOREST Premium Voal Scarf Hijab Lasercut",
      category: "Hijab",
      price: "10",
      image: "/images/products/hijab-2.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 18,
      name: "La Vierra Signature Scarf Grateful Series motif Adiba",
      category: "Hijab",
      price: "11",
      image: "/images/products/hijab-3.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 19,
      name: "The Monseur Gallery Dress Hitam Midi Fashion Korea Style",
      category: "Gaun",
      price: "25",
      image: "/images/products/dress-1.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 20,
      name: "Crop Wrap Top Wanita Terbaru Korean Style Kemeja Lengan Panjang",
      category: "Baju",
      price: "20",
      image: "/images/products/baju-7.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
  ];